print ("adding a file in git to pull it later")
print ("is it gonna delete this line after i pull?")
print ("well lets see now in local editor")
print ("adding a line to see if they colide")
print ("adding line numb5")
